### ISSUE TITLE
When drawing the map of the Japanese navigation function, the CPU usage rate of the homescreen increases significantly.

### ISSUE THREAD

**Issue by tomohiroshohi-main** [toyota-connected/ivi-homescreen-plugins#53]
## Improvement points
Do you know why the CPU load is increasing?<br>
Is there any way to improve it?<br>

## summary
When drawing the map of the Japanese navigation function, the CPU usage rate of the homescreen increases significantly.<br>

## Detail
1. Set Navi on the Home screen.
2. reboot
3. Transition from home to navigation function
4. Transition from navigation to Apps function
When transitioning from home to the navigation function, the CPU is high because both navigations are present, but when transitioning from the navigation to the Apps function, the CPU usage rate drops significantly, perhaps because the rendering process for the navigation disappears.<br>
Additionally, if processing becomes heavy on the navrender side, such as displaying POIs on the navigation, the CPU usage of homescreen will also increase.

(video removed)

**Comment by jwinarske** [comment]
@tomohiroshohi-main also note this is a public repo

**Comment by tomohiroshohi-main** [comment]
Sorry, I created an issue without knowing this was a public issue.<br>
This matter will be closed. I would like to delete it completely if possible, is that possible?<br>
